<?php

namespace Drupal\devjobs_module\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

class DevjobsForm extends FormBase {
  public function getFormId() {
    return 'devjobs_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    // TODO: Implement buildForm() method.
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    // TODO: Implement submitForm() method.
  }

  protected function getRequest() {
    return parent::getRequest(); // TODO: Change the autogenerated stub
  }

}
